# -*- coding: utf-8 -*-
import pytest

try:
    from chython import MoleculeContainer, smiles, inchi, to_inchi, inchi_key
    # importing the function always works; the shared library is what may be missing
    from chython.files.libinchi.wrapper import lib as _inchi_lib

    HAS_INCHI = _inchi_lib is not None
except ImportError:
    HAS_INCHI = False


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_parse_ethanol():
    mol = inchi('InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3')
    assert len(mol) == 3
    assert 'O' in {a.atomic_symbol for _, a in mol.atoms()}


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_parse_benzene():
    mol = inchi('InChI=1S/C6H6/c1-2-4-6-5-3-1/h1-6H')
    assert len(mol) == 6


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_parse_charged():
    mol = inchi('InChI=1S/Na.H2O/h;1H2/q+1;/p-1')
    assert mol is not None


# expected values generated by RDKit Chem.MolToInchi / Chem.MolToInchiKey
inchi_cases = [
    ('CCO', 'InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3', 'LFQSCWFLJHTTHZ-UHFFFAOYSA-N'),
    # aromatic input is kekulized on a copy
    ('CC(=O)Oc1ccccc1C(=O)O', 'InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)',
     'BSYNRYMUTXBXSQ-UHFFFAOYSA-N'),
    # disconnected components and charges
    ('[Na+].[O-]C(=O)C', 'InChI=1S/C2H4O2.Na/c1-2(3)4;/h1H3,(H,3,4);/q;+1/p-1', 'VMHLLURERBWHNL-UHFFFAOYSA-M'),
    ('C[N+](C)(C)C.[Cl-]', 'InChI=1S/C4H12N.ClH/c1-5(2,3)4;/h1-4H3;1H/q+1;/p-1', 'OKIZCWYLBDKLSU-UHFFFAOYSA-M'),
    ('O=[N+]([O-])c1ccccc1', 'InChI=1S/C6H5NO2/c8-7(9)6-4-2-1-3-5-6/h1-5H', 'LQNUZADURLCDLV-UHFFFAOYSA-N'),
    # isotopes, on the atom itself and on explicit hydrogens
    ('[13CH3]C(=O)O', 'InChI=1S/C2H4O2/c1-2(3)4/h1H3,(H,3,4)/i1+1', 'QTBSBXVTEAMEQO-OUBTZVSYSA-N'),
    ('[2H]C([2H])([2H])O', 'InChI=1S/CH4O/c1-2/h2H,1H3/i1D3', 'OKKJLVBELUTLKV-FIBGUPNXSA-N'),
    # radical
    ('[CH3]', 'InChI=1S/CH3/h1H3', 'WCYWZMWISLQXQU-UHFFFAOYSA-N'),
    # tetrahedral stereo, both enantiomers
    ('C[C@H](N)C(=O)O', 'InChI=1S/C3H7NO2/c1-2(4)3(5)6/h2H,4H2,1H3,(H,5,6)/t2-/m0/s1', 'QNAYBMKLOCPYGJ-REOHCLBHSA-N'),
    ('C[C@@H](N)C(=O)O', 'InChI=1S/C3H7NO2/c1-2(4)3(5)6/h2H,4H2,1H3,(H,5,6)/t2-/m1/s1', 'QNAYBMKLOCPYGJ-UWTATZPHSA-N'),
    # quaternary centre: four explicit neighbors
    ('C[C@](N)(F)Cl', 'InChI=1S/C2H5ClFN/c1-2(3,4)5/h5H2,1H3/t2-/m1/s1', 'OPMWDTBLHRBOPV-UWTATZPHSA-N'),
    # cis-trans
    ('F/C=C/F', 'InChI=1S/C2H2F2/c3-1-2-4/h1-2H/b2-1+', 'WFLOTYSKFUPZQB-OWOJBTEDSA-N'),
    ('F/C=C\\F', 'InChI=1S/C2H2F2/c3-1-2-4/h1-2H/b2-1-', 'WFLOTYSKFUPZQB-UPHRSURJSA-N'),
    ('C/C=C/C=C\\C', 'InChI=1S/C6H10/c1-3-5-6-4-2/h3-6H,1-2H3/b5-3-,6-4+', 'APPOKADJQUIAHP-CIIODKQPSA-N'),
    # both at once
    ('N[C@@H](Cc1ccccc1)C(=O)O',
     'InChI=1S/C9H11NO2/c10-8(9(11)12)6-7-4-2-1-3-5-7/h1-5,8H,6,10H2,(H,11,12)/t8-/m0/s1',
     'COLNVLDHVKWLRT-QMMMGPOBSA-N'),
    ('CC(=O)[C@@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C',
     'InChI=1S/C21H30O2/c1-13(22)17-6-7-18-16-5-4-14-12-15(23)8-10-20(14,2)19(16)9-11-21(17,18)3/'
     'h12,16-19H,4-11H2,1-3H3/t16-,17-,18-,19-,20-,21+/m0/s1', 'RJKFOVLPORLFTN-HXIANDDZSA-N'),
]


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
@pytest.mark.parametrize('smi, string, key', inchi_cases)
def test_inchi_write(smi, string, key):
    mol = smiles(smi)
    assert to_inchi(mol) == string
    assert inchi_key(mol) == key


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
@pytest.mark.parametrize('smi, string, key', inchi_cases)
def test_inchi_write_explicit_hydrogens(smi, string, key):
    mol = smiles(smi)
    mol.explicify_hydrogens()
    assert to_inchi(mol) == string


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
@pytest.mark.parametrize('mark, string', [(True, 'InChI=1S/C5H8/c1-3-5-4-2/h3-4H,1-2H3/t5-/m1/s1'),
                                          (False, 'InChI=1S/C5H8/c1-3-5-4-2/h3-4H,1-2H3/t5-/m0/s1')])
def test_inchi_write_allene(mark, string):
    mol = smiles('CC=C=CC')  # the SMILES parser drops allene stereo, so set it directly
    c = next(iter(mol.stereogenic_allenes))
    nn, nm, *_ = mol.stereogenic_allenes[c]
    mol.add_atom_stereo(c, (nn, nm), mark)
    assert to_inchi(mol) == string
    assert to_inchi(inchi(string)) == string  # the reader used to invert the allene parity


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
@pytest.mark.parametrize('wedge, string', [(1, 'InChI=1S/C5H8/c1-3-5-4-2/h3-4H,1-2H3/t5-/m0/s1'),
                                           (-1, 'InChI=1S/C5H8/c1-3-5-4-2/h3-4H,1-2H3/t5-/m1/s1')])
def test_inchi_write_allene_matches_the_drawn_geometry(wedge, string):
    # penta-2,3-diene drawn along x, the right hand pair in the paper, the left hand one out of it.
    # libINCHI reads the same geometry as m0 when the wedged methyl points at the viewer
    mol = MoleculeContainer()
    n = [mol.add_atom('C', xy=xy) for xy in
         ((-2., .6), (-1.3, 0.), (0., 0.), (1.3, 0.), (2., 1.2))]
    for i in range(4):
        mol.add_bond(n[i], n[i + 1], 1 if i in (0, 3) else 2)
    mol.add_wedge(n[1], n[0], wedge)
    assert to_inchi(mol) == string


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_write_ignore_stereo():
    mol = smiles('C[C@H](N)C(=O)O')
    assert to_inchi(mol, ignore_stereo=True) == 'InChI=1S/C3H7NO2/c1-2(4)3(5)6/h2H,4H2,1H3,(H,5,6)'


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_write_options():
    mol = smiles('CC(=O)Oc1ccccc1C(=O)O')
    assert to_inchi(mol, options=('FixedH',)).startswith('InChI=1/')


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_write_keeps_molecule_aromatic():
    mol = smiles('c1ccccc1')
    to_inchi(mol)
    assert all(b == 4 for *_, b in mol.bonds())


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_roundtrip():
    for smi, string, _ in inchi_cases:
        if '/i1D3' in string:
            continue  # the parser adds one D atom per isotope layer entry instead of the stated count
        assert to_inchi(inchi(string)) == string


@pytest.mark.skipif(not HAS_INCHI, reason='libinchi not available')
def test_inchi_write_inplace_kekulizes_the_given_molecule():
    aromatic, kekulized = smiles('c1ccccc1'), smiles('c1ccccc1')
    assert to_inchi(aromatic) == to_inchi(kekulized, inplace=True)
    assert all(b == 4 for *_, b in aromatic.bonds())
    assert not any(b == 4 for *_, b in kekulized.bonds())
